/**
 * Generated by Agitar build: JUnitFactory Version 2.1.0.000576 (Build date: Oct 19, 2007) [2.1.0.000576]
 * JDK Version: 1.5.0_11
 *
 * Generated on Nov 6, 2007 1:37:05 PM
 * Time to generate: 00:12.850 seconds
 *
 */

package org.crap4j.crap4jeclipse.preferences;

import com.agitar.lib.junit.AgitarTestCase;

public class PreferenceConstantsAgitarTest extends AgitarTestCase {
    
    public Class getTargetClass()  {
        return PreferenceConstants.class;
    }
    
    public void testConstructor() throws Throwable {
        new PreferenceConstants();
        assertTrue("Test call resulted in expected outcome", true);
    }
}

