/**
 * Generated by Agitar build: JUnitFactory Version 2.1.0.000576 (Build date: Oct 19, 2007) [2.1.0.000576]
 * JDK Version: 1.5.0_11
 *
 * Generated on Oct 26, 2007 3:58:22 PM
 * Time to generate: 00:13.933 seconds
 *
 */

package org.crap4j.complexity;

import com.agitar.lib.junit.AgitarTestCase;

public class NodeAgitarTest extends AgitarTestCase {
    
    public Class getTargetClass()  {
        return Node.class;
    }
    
    public void testConstructor() throws Throwable {
        Node node = (Node) callPrivateMethod("org.crap4j.complexity.Node", "<init>", new Class[] {Class.forName("com.agitar.org.objectweb.asm.tree.analysis.Frame")}, null, new Object[] {new Node(100, 1000)});
        assertEquals("node.successors.size()", 0, node.successors.size());
    }
    
    public void testConstructor1() throws Throwable {
        Node node = new Node(100, 1000);
        assertEquals("node.successors.size()", 0, node.successors.size());
    }
    
    public void testConstructorThrowsNegativeArraySizeException() throws Throwable {
        try {
            new Node(-16, 0);
            fail("Expected NegativeArraySizeException to be thrown");
        } catch (NegativeArraySizeException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
        }
    }
    
    public void testConstructorThrowsNullPointerException() throws Throwable {
        try {
            callPrivateMethod("org.crap4j.complexity.Node", "<init>", new Class[] {Class.forName("com.agitar.org.objectweb.asm.tree.analysis.Frame")}, null, new Object[] {null});
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
        }
    }
}

