/**
 * Generated by Agitar build: JUnitFactory Version 2.1.1.000614 (Build date: Nov 19, 2007) [2.1.1.000614]
 * JDK Version: 1.5.0_11
 *
 * Generated on Nov 27, 2007 5:08:51 PM
 * Time to generate: 00:12.218 seconds
 *
 */

package org.crap4j.util;

import com.agitar.lib.junit.AgitarTestCase;

public class TestClassCheckerAgitarTest extends AgitarTestCase {
    
    public Class getTargetClass()  {
        return TestClassChecker.class;
    }
    
    public void testConstructor() throws Throwable {
        new TestClassChecker();
        assertTrue("Test call resulted in expected outcome", true);
    }
}

