/**
 * Generated by Agitar build: JUnitFactory Version 2.1.1.000614 (Build date: Nov 19, 2007) [2.1.1.000614]
 * JDK Version: 1.5.0_11
 *
 * Generated on Nov 27, 2007 4:11:30 PM
 * Time to generate: 00:16.069 seconds
 *
 */

package org.crap4j.util;

import com.agitar.lib.junit.AgitarTestCase;
import java.util.ArrayList;
import java.util.List;

public class XmlUtilAgitarTest extends AgitarTestCase {
    
    public Class getTargetClass()  {
        return XmlUtil.class;
    }
    
    public void testConstructor() throws Throwable {
        new XmlUtil();
        assertTrue("Test call resulted in expected outcome", true);
    }
    
    public void testCollectionToXml() throws Throwable {
        MyStringBuilder s = new MyStringBuilder();
        List collection = new ArrayList(100);
        collection.add("");
        XmlUtil.collectionToXml(s, "testXmlUtilCollectionName", "testXmlUtilItemName", collection);
        assertEquals("(ArrayList) collection.size()", 1, collection.size());
    }
    
    public void testCollectionToXml1() throws Throwable {
        MyStringBuilder s = new MyStringBuilder();
        List collection = new ArrayList(100);
        XmlUtil.collectionToXml(s, "testXmlUtilCollectionName", "testXmlUtilItemName", collection);
        assertEquals("(ArrayList) collection.size()", 0, collection.size());
    }
    
    public void testItemToXml() throws Throwable {
        MyStringBuilder s = new MyStringBuilder();
        XmlUtil.itemToXml(s, "testXmlUtilItemName", "testXmlUtilItem");
        assertTrue("Test call resulted in expected outcome", true);
    }
    
    public void testCollectionToXmlThrowsNullPointerException() throws Throwable {
        List collection = new ArrayList(100);
        try {
            XmlUtil.collectionToXml(null, "testXmlUtilCollectionName", "testXmlUtilItemName", collection);
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(XmlUtil.class, ex);
            assertEquals("(ArrayList) collection.size()", 0, collection.size());
        }
    }
    
    public void testCollectionToXmlThrowsNullPointerException1() throws Throwable {
        MyStringBuilder s = new MyStringBuilder();
        try {
            XmlUtil.collectionToXml(s, "testXmlUtilCollectionName", "testXmlUtilItemName", null);
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertEquals("s.currentIndentation", 2, ((Number) getPrivateField(s, "currentIndentation")).intValue());
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(XmlUtil.class, ex);
        }
    }
    
    public void testItemToXmlThrowsNullPointerException() throws Throwable {
        try {
            XmlUtil.itemToXml(null, "testXmlUtilItemName", "testXmlUtilItem");
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(XmlUtil.class, ex);
        }
    }
}

