/**
 * Generated by Agitar build: JUnitFactory Version 2.1.0.000576 (Build date: Oct 19, 2007) [2.1.0.000576]
 * JDK Version: 1.5.0_11
 *
 * Generated on Oct 26, 2007 3:57:21 PM
 * Time to generate: 00:19.729 seconds
 *
 */

package org.crap4j;

import com.agitar.lib.junit.AgitarTestCase;

public class MethodComplexityAgitarTest extends AgitarTestCase {
    
    public Class getTargetClass()  {
        return MethodComplexity.class;
    }
    
    public void testConstructor() throws Throwable {
        MethodComplexity methodComplexity = new MethodComplexity("testMethodComplexityMethodSignature", ".", "testMethodComplexityMethodName", "testMethodComplexityMethodDescriptor", "testMethodComplexityJava5Signature", 100, "testMethodComplexityPrettyMethodSignature");
        assertEquals("methodComplexity.getMethodName()", "testMethodComplexityMethodName", methodComplexity.getMethodName());
        assertEquals("methodComplexity.getClassName()", ".", methodComplexity.getClassName());
        assertEquals("methodComplexity.getJava5Signature()", "testMethodComplexityJava5Signature", methodComplexity.getJava5Signature());
        assertEquals("methodComplexity.getPackageName()", "", methodComplexity.getPackageName());
        assertEquals("methodComplexity.pkgclassName", ".", getPrivateField(methodComplexity, "pkgclassName"));
        assertEquals("methodComplexity.getMethodDescriptor()", "testMethodComplexityMethodDescriptor", methodComplexity.getMethodDescriptor());
        assertEquals("methodComplexity.prettyMethodSignature()", "testMethodComplexityPrettyMethodSignature", methodComplexity.prettyMethodSignature());
        assertEquals("methodComplexity.matchingMethodSignature", "..testMethodComplexityMethodNametestMethodComplexityMethodDescriptor", methodComplexity.matchingMethodSignature);
        assertEquals("methodComplexity.getComplexity()", 100, methodComplexity.getComplexity());
    }
    
    public void testConstructor1() throws Throwable {
        MethodComplexity methodComplexity = new MethodComplexity("testMethodComplexityMethodSignature", "{.", "testMethodComplexityMethodName", "testMethodComplexityMethodDescriptor", "testMethodComplexityJava5Signature", 100, "testMethodComplexityPrettyMethodSignature");
        assertEquals("methodComplexity.getMethodName()", "testMethodComplexityMethodName", methodComplexity.getMethodName());
        assertEquals("methodComplexity.getClassName()", "", methodComplexity.getClassName());
        assertEquals("methodComplexity.getJava5Signature()", "testMethodComplexityJava5Signature", methodComplexity.getJava5Signature());
        assertEquals("methodComplexity.getPackageName()", "{", methodComplexity.getPackageName());
        assertEquals("methodComplexity.pkgclassName", "{.", getPrivateField(methodComplexity, "pkgclassName"));
        assertEquals("methodComplexity.getMethodDescriptor()", "testMethodComplexityMethodDescriptor", methodComplexity.getMethodDescriptor());
        assertEquals("methodComplexity.prettyMethodSignature()", "testMethodComplexityPrettyMethodSignature", methodComplexity.prettyMethodSignature());
        assertEquals("methodComplexity.matchingMethodSignature", "{..testMethodComplexityMethodNametestMethodComplexityMethodDescriptor", methodComplexity.matchingMethodSignature);
        assertEquals("methodComplexity.getComplexity()", 100, methodComplexity.getComplexity());
    }
    
    public void testConstructor2() throws Throwable {
        MethodComplexity methodComplexity = new MethodComplexity("testMethodComplexityMethodSignature", "testMethodComplexityPkgclassName", "testMethodComplexityMethodName", "testMethodComplexityMethodDescriptor", "testMethodComplexityJava5Signature", 100, "testMethodComplexityPrettyMethodSignature");
        assertEquals("methodComplexity.getMethodName()", "testMethodComplexityMethodName", methodComplexity.getMethodName());
        assertEquals("methodComplexity.getClassName()", "testMethodComplexityPkgclassName", methodComplexity.getClassName());
        assertEquals("methodComplexity.getJava5Signature()", "testMethodComplexityJava5Signature", methodComplexity.getJava5Signature());
        assertEquals("methodComplexity.getPackageName()", "", methodComplexity.getPackageName());
        assertEquals("methodComplexity.pkgclassName", "testMethodComplexityPkgclassName", getPrivateField(methodComplexity, "pkgclassName"));
        assertEquals("methodComplexity.getMethodDescriptor()", "testMethodComplexityMethodDescriptor", methodComplexity.getMethodDescriptor());
        assertEquals("methodComplexity.prettyMethodSignature()", "testMethodComplexityPrettyMethodSignature", methodComplexity.prettyMethodSignature());
        assertEquals("methodComplexity.matchingMethodSignature", "testMethodComplexityPkgclassName.testMethodComplexityMethodNametestMethodComplexityMethodDescriptor", methodComplexity.matchingMethodSignature);
        assertEquals("methodComplexity.getComplexity()", 100, methodComplexity.getComplexity());
    }
    
    public void testGetClassName() throws Throwable {
        MethodComplexity methodComplexity = new MethodComplexity("testMethodComplexityMethodSignature", "testMethodComplexityPkgclassName", "testMethodComplexityMethodName", "testMethodComplexityMethodDescriptor", "testMethodComplexityJava5Signature", 100, "testMethodComplexityPrettyMethodSignature");
        String result = methodComplexity.getClassName();
        assertEquals("result", "testMethodComplexityPkgclassName", result);
    }
    
    public void testGetComplexity() throws Throwable {
        MethodComplexity methodComplexity = new MethodComplexity("testMethodComplexityMethodSignature", "testMethodComplexityPkgclassName", "testMethodComplexityMethodName", "testMethodComplexityMethodDescriptor", "testMethodComplexityJava5Signature", 100, "testMethodComplexityPrettyMethodSignature");
        int result = methodComplexity.getComplexity();
        assertEquals("result", 100, result);
    }
    
    public void testGetComplexity1() throws Throwable {
        MethodComplexity methodComplexity = new MethodComplexity("testMethodComplexityMethodSignature", "testMethodComplexityPkgclassName", "testMethodComplexityMethodName", "testMethodComplexityMethodDescriptor", "testMethodComplexityJava5Signature", 0, "testMethodComplexityPrettyMethodSignature");
        int result = methodComplexity.getComplexity();
        assertEquals("result", 0, result);
    }
    
    public void testGetJava5Signature() throws Throwable {
        MethodComplexity methodComplexity = new MethodComplexity("testMethodComplexityMethodSignature", "testMethodComplexityPkgclassName", "testMethodComplexityMethodName", "testMethodComplexityMethodDescriptor", "testMethodComplexityJava5Signature", 100, "testMethodComplexityPrettyMethodSignature");
        String result = methodComplexity.getJava5Signature();
        assertEquals("result", "testMethodComplexityJava5Signature", result);
    }
    
    public void testGetMethodDescriptor() throws Throwable {
        MethodComplexity methodComplexity = new MethodComplexity("testMethodComplexityMethodSignature", "testMethodComplexityPkgclassName", "testMethodComplexityMethodName", "testMethodComplexityMethodDescriptor", "testMethodComplexityJava5Signature", 100, "testMethodComplexityPrettyMethodSignature");
        String result = methodComplexity.getMethodDescriptor();
        assertEquals("result", "testMethodComplexityMethodDescriptor", result);
    }
    
    public void testGetMethodName() throws Throwable {
        MethodComplexity methodComplexity = new MethodComplexity("testMethodComplexityMethodSignature", "testMethodComplexityPkgclassName", "testMethodComplexityMethodName", "testMethodComplexityMethodDescriptor", "testMethodComplexityJava5Signature", 100, "testMethodComplexityPrettyMethodSignature");
        String result = methodComplexity.getMethodName();
        assertEquals("result", "testMethodComplexityMethodName", result);
    }
    
    public void testGetPackageName() throws Throwable {
        MethodComplexity methodComplexity = new MethodComplexity("testMethodComplexityMethodSignature", "testMethodComplexityPkgclassName", "testMethodComplexityMethodName", "testMethodComplexityMethodDescriptor", "testMethodComplexityJava5Signature", 100, "testMethodComplexityPrettyMethodSignature");
        String result = methodComplexity.getPackageName();
        assertEquals("result", "", result);
    }
    
    public void testGetSigOrDescriptor() throws Throwable {
        MethodComplexity methodComplexity = new MethodComplexity("testMethodComplexityMethodSignature", "testMethodComplexityPkgclassName", "testMethodComplexityMethodName", "testMethodComplexityMethodDescriptor", " ", 100, "testMethodComplexityPrettyMethodSignature");
        String result = methodComplexity.getSigOrDescriptor();
        assertEquals("result", " ", result);
    }
    
    public void testGetSigOrDescriptor1() throws Throwable {
        MethodComplexity methodComplexity = new MethodComplexity("testMethodComplexityMethodSignature", "testMethodComplexityPkgclassName", "testMethodComplexityMethodName", "testMethodComplexityMethodDescriptor", "", 100, "testMethodComplexityPrettyMethodSignature");
        String result = methodComplexity.getSigOrDescriptor();
        assertEquals("result", "testMethodComplexityMethodDescriptor", result);
    }
    
    public void testGetSigOrDescriptor2() throws Throwable {
        MethodComplexity methodComplexity = new MethodComplexity("testMethodComplexityMethodSignature", "testMethodComplexityPkgclassName", "testMethodComplexityMethodName", "testMethodComplexityMethodDescriptor", null, 100, "testMethodComplexityPrettyMethodSignature");
        String result = methodComplexity.getSigOrDescriptor();
        assertEquals("result", "testMethodComplexityMethodDescriptor", result);
    }
    
    public void testMakeClassName() throws Throwable {
        MethodComplexity methodComplexity = new MethodComplexity("testMethodComplexityMethodSignature", "testMethodComplexityPkgclassName", "testMethodComplexityMethodName", "testMethodComplexityMethodDescriptor", "testMethodComplexityJava5Signature", 100, "testMethodComplexityPrettyMethodSignature");
        String result = (String) callPrivateMethod("org.crap4j.MethodComplexity", "makeClassName", new Class[] {}, methodComplexity, new Object[] {});
        assertEquals("result", "testMethodComplexityPkgclassName", result);
    }
    
    public void testMakePackageName() throws Throwable {
        MethodComplexity methodComplexity = new MethodComplexity("testMethodComplexityMethodSignature", "testMethodComplexityPkgclassName", "testMethodComplexityMethodName", "testMethodComplexityMethodDescriptor", "testMethodComplexityJava5Signature", 100, "testMethodComplexityPrettyMethodSignature");
        String result = (String) callPrivateMethod("org.crap4j.MethodComplexity", "makePackageName", new Class[] {}, methodComplexity, new Object[] {});
        assertEquals("result", "", result);
    }
    
    public void testMakePackageName1() throws Throwable {
        MethodComplexity methodComplexity = new MethodComplexity("testMethodComplexityMethodSignature", ".", "testMethodComplexityMethodName", "testMethodComplexityMethodDescriptor", "testMethodComplexityJava5Signature", 100, "testMethodComplexityPrettyMethodSignature");
        String result = (String) callPrivateMethod("org.crap4j.MethodComplexity", "makePackageName", new Class[] {}, methodComplexity, new Object[] {});
        assertEquals("result", "", result);
    }
    
    public void testPrettyMethodSignature() throws Throwable {
        MethodComplexity methodComplexity = new MethodComplexity("testMethodComplexityMethodSignature", "testMethodComplexityPkgclassName", "testMethodComplexityMethodName", "testMethodComplexityMethodDescriptor", "testMethodComplexityJava5Signature", 100, "testMethodComplexityPrettyMethodSignature");
        String result = methodComplexity.prettyMethodSignature();
        assertEquals("result", "testMethodComplexityPrettyMethodSignature", result);
    }
    
    public void testToString() throws Throwable {
        MethodComplexity methodComplexity = new MethodComplexity("testMethodComplexityMethodSignature", "testMethodComplexityPkgclassName", "testMethodComplexityMethodName", "testMethodComplexityMethodDescriptor", "testMethodComplexityJava5Signature", 100, "testMethodComplexityPrettyMethodSignature");
        String result = methodComplexity.toString();
        assertEquals("result", "testMethodComplexityPkgclassName.testMethodComplexityMethodNametestMethodComplexityMethodDescriptor : 100", result);
    }
    
    public void testConstructorThrowsNullPointerException() throws Throwable {
        try {
            new MethodComplexity("testMethodComplexityMethodSignature", null, "testMethodComplexityMethodName", "testMethodComplexityMethodDescriptor", "testMethodComplexityJava5Signature", 100, "testMethodComplexityPrettyMethodSignature");
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(MethodComplexity.class, ex);
        }
    }
}

