/**
 * Generated by Agitar build: JUnitFactory Version 2.0.3.000562 (Build date: Oct 09, 2007) [2.0.3.000562]
 * JDK Version: 1.5.0_11
 *
 * Generated on Oct 15, 2007 5:43:48 PM
 * Time to generate: 00:24.701 seconds
 *
 */

package org.crap4j.crap4jeclipse.popup.actions;

import com.agitar.lib.junit.AgitarTestCase;
import com.agitar.lib.mockingbird.Mockingbird;
import org.crap4j.crap4jeclipse.views.Crap4jView;
import org.eclipse.jface.dialogs.MessageDialog;
import org.eclipse.jface.viewers.TreeSelection;
import org.eclipse.swt.widgets.Shell;

public class Crap4jActionAgitarTest extends AgitarTestCase {
    
    public Class getTargetClass()  {
        return Crap4jAction.class;
    }
    
    public void testConstructor() throws Throwable {
        new Crap4jAction();
        assertTrue("Test call resulted in expected outcome", true);
    }
    
    public void testRun() throws Throwable {
        Crap4jAction crap4jAction = new Crap4jAction();
        Mockingbird.enterRecordingMode();
        Shell shell = (Shell) Mockingbird.getProxyObject(Shell.class);
        Mockingbird.replaceObjectForRecording(Shell.class, "<init>()", shell);
        MessageDialog.openInformation(shell, "Crap4jEclipse Plug-in", "Run Crap4j was executed.");
        Mockingbird.setNormalReturnForVoid();
        Mockingbird.enterTestMode(Crap4jAction.class);
        crap4jAction.run(null);
        assertTrue("Test call resulted in expected outcome", true);
    }
    
    public void testSelectionChanged() throws Throwable {
        new Crap4jAction().selectionChanged(null, new TreeSelection());
        assertTrue("Test call resulted in expected outcome", true);
    }
    
    public void testSetActivePart() throws Throwable {
        new Crap4jAction().setActivePart(null, new Crap4jView());
        assertTrue("Test call resulted in expected outcome", true);
    }
}

